export const POPULAR_DEVICES = [
  // Apple
  'iPhone 15 Pro Max',
  'iPhone 15 Pro',
  'iPhone 15 Plus',
  'iPhone 15',
  'iPhone 14 Pro Max',
  'iPhone 14 Pro',
  'iPhone 13 Pro Max',
  'iPhone 13 Pro',
  'iPhone 13',
  'iPhone 12 Pro Max',
  'iPhone 12',
  'iPhone 11 Pro Max',
  'iPhone 11',
  'iPhone XS Max',
  'iPhone X/XS',
  'iPhone 8 Plus',
  'iPad Pro 12.9',
  'iPad Pro 11',
  'iPad Air 5',
  'iPad Gen 10',
  'MacBook Pro 14 M1/M2/M3',
  'MacBook Pro 16',
  'MacBook Air M1/M2',

  // Samsung
  'Samsung S24 Ultra',
  'Samsung S24 Plus',
  'Samsung S23 Ultra',
  'Samsung S22 Ultra',
  'Samsung Z Fold 5',
  'Samsung Z Flip 5',
  'Samsung A55',
  'Samsung A35',
  'Samsung A25',
  'Samsung A15',
  'Samsung A05s',
  'Samsung Tab S9',

  // Xiaomi / Oppo / Vivo
  'Xiaomi 14 Ultra',
  'Xiaomi 13T',
  'Redmi Note 13 Pro',
  'Redmi Note 12',
  'Oppo Find N3',
  'Oppo Reno 10',
  'Vivo X100',
  'Vivo V29',

  // Laptops
  'Dell XPS 13',
  'Dell XPS 15',
  'Dell Inspiron',
  'Dell Latitude',
  'HP Spectre',
  'HP Envy',
  'HP Pavilion',
  'Asus ROG Strix',
  'Asus TUF Gaming',
  'Asus ZenBook',
  'Asus VivoBook',
  'Lenovo ThinkPad X1',
  'Lenovo Legion',
  'Lenovo IdeaPad',
  'Acer Nitro 5',
  'Acer Swift',
  'MSI Katana',
  'MSI Modern',

  // Others
  'Apple Watch Series 9',
  'Apple Watch Ultra',
  'AirPods Pro 2',
  'Sony WH-1000XM5',
  'JBL Speaker',
  'May tinh de ban (PC)',
  'Man hinh may tinh',
  'May in',
  'Khac',
];
